### ISSUE TITLE
Crash on starting the application

### ISSUE THREAD

**Issue by stezan** [ScreebApp/sdk-android-public#2]
Hello, I have a problem with the Screeb Android SDK, that makes the app crash as soon as it opens.

I am using the version `1.10.0` and I initialised the SDK in the `onCreate` of the `Application` both with

(the
```
Screeb.Builder()
        .withContext(this)
        .withChannelId("<website-id>")
        .build()
```
reported in the documentation does not work with the new version, the `Builder()` is an unknown reference).

So I tried both with

```
ScreebBuilder.Builder()
            .withContext(this)
            .withChannelId("<channel-id>")
            .build()
```

and

`Screeb.initSdk(this, "<channel-id>")`, but it crash as soon as the app opens with the stacktrace

```
java.lang.NoSuchFieldError: No field INSTANCE of type Lapp/screeb/sdk/Screeb; in class Lapp/screeb/sdk/Screeb; or its superclasses (declaration of 'app.screeb.sdk.Screeb' appears in /data/app/com.app.name.test==/base.apk)
        at com.appname.Application.onCreate(Application.kt:62)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6710)
        at android.app.ActivityThread.access$1300(ActivityThread.java:226)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1898)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7615)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```
.

Can you help me? Thanks

**Comment by samber** [comment]
Closing as the problem was solved
